export type Mode = "brand" | "team" | "creator";
export type Creator = {id:string;name:string;handle:string;category:string;platform:string;followers:number;views:number;us:number;engagement:number;quote:number;cost?:number;reason:string;deliverables:string;selected:boolean;confirmed:boolean;color:string;stage:string};
export type Version = {id:string;number:number;caption:string;script:string;file?:{key:string;name:string;type:string};status:"pending"|"changes"|"approved";at:string};
export type Draft = {id:string;creatorId:string;versions:Version[];comments:{id:string;versionId:string;author:string;text:string;at:string}[];published:boolean;publishedAt?:string};
export type DemoState = {revision:number;creators:Creator[];drafts:Draft[];activity:{text:string;at:string}[];brief:string;geoTasks:string[]};
export const money=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);
export const compact=(v:number)=>new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1}).format(v);
export function seedDemo():DemoState{return {revision:0,brief:"以美国美妆受众为核心，围绕雕花口红的东方设计与日常妆容场景，完成一轮创作者种草。品牌曝光为先；首批内容采用 Instagram Reels 与 Stories。样品、卖点和发布文案由品牌确认。",geoTasks:[],creators:[
{id:"maya",name:"Maya Chen",handle:"maya.glow · 示例账号",category:"东方妆容 / 美妆教程",platform:"Instagram",followers:128000,views:62400,us:76,engagement:3.8,quote:3200,cost:3200,reason:"擅长把产品细节融入日常妆容；受众与美国美妆新品推广方向匹配。",deliverables:"1 条 Reel + 3 帧 Story · 自然发布，不含广告使用权",selected:true,confirmed:true,color:"#d9e8ef",stage:"制作中"},
{id:"olivia",name:"Olivia Brooks",handle:"olivia.beautynotes · 示例账号",category:"彩妆测评 / 真实试色",platform:"Instagram",followers:68000,views:31200,us:82,engagement:4.2,quote:2100,cost:2100,reason:"测评内容清晰，适合用近景展示雕花设计与上唇效果。",deliverables:"1 条 Reel + 2 帧 Story · 自然发布，不含广告使用权",selected:false,confirmed:false,color:"#eddcda",stage:"待确认"},
{id:"sophia",name:"Sophia Park",handle:"sophia.everyday · 示例账号",category:"生活方式 / 通勤妆容",platform:"Instagram",followers:94000,views:48700,us:71,engagement:4.7,quote:1700,cost:1700,reason:"通勤妆容和开箱内容自然，适合覆盖 Instagram 上的日常美妆场景。",deliverables:"1 条 Reel · 自然发布，不含广告使用权",selected:false,confirmed:false,color:"#e6e2f0",stage:"待确认"},
{id:"ava",name:"Ava Williams",handle:"ava.incolour · 示例账号",category:"创意彩妆 / 色彩表达",platform:"Instagram",followers:87000,views:42600,us:79,engagement:3.5,quote:2500,cost:2500,reason:"色彩表达鲜明，可用一条完整妆容强化系列辨识度。",deliverables:"1 条 Reel + 3 帧 Story · 自然发布，不含广告使用权",selected:false,confirmed:false,color:"#e4eadf",stage:"待确认"}],drafts:[{id:"draft-maya",creatorId:"maya",versions:[{id:"v1-maya",number:1,caption:"A little art in my everyday routine. Exploring the details of this engraved lipstick from Florasis. #ad #Florasis #EverydayBeauty",script:"00–05s｜近景展示雕花口红与包装。\n05–18s｜自然光下试色，描述个人使用感受。\n18–30s｜完成日常妆容；展示产品名称与广告合作标识。\n画面与文字均为脚本提案，产品功效表述须经品牌核实。",status:"pending",at:"2026-09-20T10:00:00Z"}],comments:[],published:false}],activity:[{text:"William 提交了 Maya 的第一版脚本与文案",at:"2026-09-20T10:00:00Z"},{text:"品牌已确认 Maya；另外 3 位候选人待选择",at:"2026-09-19T14:00:00Z"}],};}
export function visibleState(state:DemoState,mode:string):DemoState {if(mode==="team")return state;return {...state,creators:state.creators.map(({cost,...c})=>c)};}

export function instagramOnly(state:DemoState):DemoState {
 return {...state,brief:state.brief.replaceAll("Instagram Reels 为主，TikTok 为辅","Instagram Reels 与 Stories").replaceAll("首批内容以 Instagram Reels 与 Stories。","首批内容采用 Instagram Reels 与 Stories。").replaceAll("Instagram + TikTok","Instagram"),creators:state.creators.map(c=>{const d=state.drafts.find(d=>d.creatorId===c.id);const v=d?.versions.at(-1);return {...c,platform:"Instagram",stage:d?.published?"已发布（模拟）":v?.status==="approved"?"待发布":v?.status==="changes"?"待修改":v?.status==="pending"?"待品牌审稿":c.stage,deliverables:c.deliverables.replaceAll("TikTok 视频","Reel"),reason:c.reason.replaceAll("补充 TikTok 的触达场景","覆盖 Instagram 上的日常美妆场景")}})};
}
