import { useState, useEffect, useCallback, useRef } from "react";
import { ArrowUpRight, LayoutDashboard, Users, Clapperboard, ChartNoAxesCombined, Sparkles, ArrowRight, Check, ChevronDown, Download, FileText, CheckCircle2, MessageSquare, RefreshCw, MapPin, Languages } from "lucide-react";
import { Sidebar, SidebarProvider, SidebarContent, SidebarHeader, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarInset, SidebarTrigger } from "@/components/ui/sidebar";
import { Button } from "@/components/ui/button";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableHeader, TableHead, TableBody, TableRow, TableCell } from "@/components/ui/table";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";
import { seedDemo, money, compact, type DemoState, type Creator } from "@/lib/demo";
import { loadDemo, mediaUrl, mutateDemo } from "@/lib/demo-client";

const navigation = [["overview","项目总览", LayoutDashboard], ["creators","博主推荐", Users], ["review","内容审核", Clapperboard], ["results","投放结果", ChartNoAxesCombined], ["geo","GEO 洞察", Sparkles]] as const;
const titles:Record<string,[string,string]>={overview:["花西子 · 美国秋季推广","从一次合作开始，让品牌被更多人看见。"],creators:["找到适合品牌的声音","先看内容和受众，再决定合作的人选。"],review:["好的内容，一起打磨","在同一个地方确认文案、反馈与最终版本。"],results:["每一份投入，都有回响","内容表现、执行费用与可核验的结果。"],geo:["当用户向 AI 问起美妆","看见品牌如何被提及，找到值得改进的内容。"]};
const statusName={pending:"待品牌审核",changes:"需要修改",approved:"品牌已通过"};
const platforms=["Instagram","TikTok","YouTube"] as const;

function initials(name:string){return name.split(" ").map(x=>x[0]).slice(0,2).join("")}
function dateLabel(at:string){return new Date(at).toLocaleString("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",timeZone:"America/New_York"})}
function downloadFile(name:string,content:string,type="text/plain;charset=utf-8"){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

export default function Workspace(){
  const [view,setView]=useState("overview"),[state,setState]=useState<DemoState>(seedDemo()),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const [detail,setDetail]=useState<Creator|null>(null),[briefOpen,setBriefOpen]=useState(false),[draftId,setDraftId]=useState("draft-maya"),[versionIndex,setVersionIndex]=useState(-1),[comment,setComment]=useState(""),[filter,setFilter]=useState("all");
  const current=useRef({state,ready,busy});
  current.current={state,ready,busy};

  const reload=useCallback(async()=>{setError("");try{const data=await loadDemo();setState(data);setReady(true);}catch(e){setError((e as Error).message||"无法读取项目，请重试。");setReady(false);}},[]);
  useEffect(()=>{const url=new URL(location.href),mode=url.searchParams.get("mode"),section=url.searchParams.get("section");const validSection=navigation.some(([key])=>key===section);setView((!mode||mode==="brand")&&validSection?section!:"overview");if(mode||section&&!validSection){url.searchParams.delete("mode");if(mode&&mode!=="brand"||!validSection)url.searchParams.delete("section");history.replaceState(null,"",url);}},[]);
  useEffect(()=>{void reload()},[reload]);
  async function act(action:string,values:Record<string,unknown>={},message="已保存"){const ctx=current.current;if(!ctx.ready||ctx.busy)return false;setBusy(true);setError("");try{const data=await mutateDemo({action,mode:"brand",revision:ctx.state.revision,...values});setState(data);toast.success(message);return true}catch(e){const text=(e as Error).message;setError(text);toast.error(text);return false}finally{setBusy(false)}}
  useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:"read_campaign",title:"查看演示项目",description:"Read the current hypothetical campaign, confirmed creators, pending reviews and budget. Does not change data.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>{const s=current.current.state;return {demo:true,revision:s.revision,budget:12000,executionBudget:9600,creators:s.creators.map(c=>({id:c.id,name:c.name,quote:c.quote,selected:c.selected,confirmed:c.confirmed})),drafts:s.drafts.map(d=>({id:d.id,status:d.versions.at(-1)?.status??"awaiting_draft",published:d.published}))}}},{name:"navigate_campaign",title:"打开项目页面",description:"Navigate to a visible campaign section. Only changes the current view, never approves or publishes anything.",inputSchema:{type:"object",properties:{section:{type:"string",enum:["overview","creators","review","results","geo"]}},required:["section"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:any)=>{if(!input||Object.keys(input).length!==1||!["overview","creators","review","results","geo"].includes(input.section))throw new Error("Invalid section");setView(input.section);return {section:input.section}}}];for(const t of tools)Promise.resolve(context.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
  const go=(v:string)=>{setView(v);setError("");};
  useEffect(()=>{window.scrollTo({top:0,behavior:"instant"});},[view]);

  const disabled=!ready||busy;
  const confirmed=state.creators.filter(c=>c.confirmed),selected=state.creators.filter(c=>c.selected),newSelected=selected.filter(c=>!c.confirmed),chosenTotal=selected.reduce((s,c)=>s+c.quote,0),committed=confirmed.reduce((s,c)=>s+c.quote,0);
  const pending=state.drafts.filter(d=>d.versions.at(-1)?.status==="pending"&&!d.published),published=state.drafts.filter(d=>d.published),awaiting=state.drafts.filter(d=>!d.published);
  const draft=state.drafts.find(d=>d.id===draftId)??state.drafts[0],creator=state.creators.find(c=>c.id===draft?.creatorId),last=draft?.versions.at(-1),shownVersion=versionIndex<0?last:draft?.versions[versionIndex];
  const stage=published.length&&published.length===state.drafts.length?4:confirmed.length===state.creators.length?2:1;
  const nav=navigation;
  const title=titles[view]??titles.overview;
  const filtered=state.creators.filter(c=>filter==="all"||filter==="confirmed"&&c.confirmed||filter===c.platform);
  const metricRows=published.map((d,i)=>{const c=state.creators.find(x=>x.id===d.creatorId)!;return {creator:c.name,platform:c.platform,views:[68420,32570,52980,46150][i%4],likes:[3218,1705,2540,1930][i%4],comments:[148,89,132,102][i%4],saves:[412,218,340,289][i%4],cost:c.quote}});
  const views=metricRows.reduce((s,x)=>s+x.views,0),engagement=metricRows.reduce((s,x)=>s+x.likes+x.comments+x.saves,0);
  function selectDraft(id:string){setDraftId(id);setVersionIndex(-1);setComment("")}
  const draftPicker=<Select value={draft?.id??""} onValueChange={selectDraft}><SelectTrigger aria-label="选择创作者稿件"><SelectValue/></SelectTrigger><SelectContent>{state.drafts.map(d=><SelectItem key={d.id} value={d.id}>{state.creators.find(c=>c.id===d.creatorId)?.name}</SelectItem>)}</SelectContent></Select>;

  return <SidebarProvider>
    <Toaster richColors position="top-center"/>
    <Sidebar className="site-sidebar">
      <SidebarHeader><div className="wordmark">hOpOn<i>/</i><span>WORKSPACE</span></div><div className="workspace">F<span>花西子 Florasis<small>品牌工作空间</small></span><ChevronDown size={15}/></div></SidebarHeader>
      <SidebarContent><p className="nav-label">WORKSPACE</p><SidebarMenu>{nav.map(([key,label,Icon])=><SidebarMenuItem key={key}><SidebarMenuButton isActive={view===key} onClick={()=>go(key)}><Icon/><span>{label}</span>{key==="review"&&pending.length>0&&<b className="nav-count">{pending.length}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent>
      <SidebarFooter><div className="sidebar-note"><span className="mini-mark">h</span><p>美国市场服务<small>Creator marketing + GEO</small></p></div><div className="account"><span>FL</span><p>Florasis 团队<small>品牌负责人</small></p></div></SidebarFooter>
    </Sidebar>
    <SidebarInset>
      <header className="topbar"><div><SidebarTrigger aria-label="展开或收起导航"/><span>品牌合作空间</span><i>/</i><strong>{nav.find(n=>n[0]===view)?.[1]??"项目"}</strong></div><div className="role"><span className="demo-pill">虚拟项目演示</span></div></header>
      <main className="canvas">
        <div className="eyebrow">CAMPAIGN / 001 <span>美国 · 多平台创作者</span><button className="sync" onClick={()=>reload()} disabled={busy} aria-label="刷新项目"><RefreshCw size={12}/>{busy?"保存中":ready?"本机已保存":"读取中"}</button></div>
        <div className="page-title"><div><h1>{title[0]}</h1><p>{title[1]}</p></div>{view==="overview"&&<Button className="primary-action" onClick={()=>go("creators")}>查看推荐博主 <ArrowUpRight size={17}/></Button>}{view==="results"&&<Button variant="outline" onClick={()=>downloadFile("hOpOn-Florasis-demo-report.csv","\uFEFF演示报告：所有数据为模拟，非实际投放\n创作者,平台,播放量,点赞,评论,收藏,执行报价USD\n"+metricRows.map(x=>Object.values(x).join(",")).join("\n")+"\n品牌总预算,12000\n服务费,2400\n执行预算,9600\n转化订单,未接入\n", "text/csv;charset=utf-8")}><Download size={16}/> 导出报告</Button>}</div>
        {error&&<div role="alert" className="error-box">{error}<Button variant="outline" size="sm" onClick={()=>reload()}>刷新项目</Button></div>}

        {view==="overview"&&<>
          <section className="campaign-banner"><img src="/florasis-demo/florasis-hero.jpg" alt="花西子官方美妆视觉，仅作演示参考"/><div className="banner-copy"><span className="tag">正在进行 · {pending.length?"内容审核":"博主合作"}</span><h2>Beauty.<br/>Beyond borders<span className="red-period">.</span></h2><p>以东方美学为起点，连接美国美妆受众。</p><div className="banner-meta"><span>2026.10.01 — 10.31</span><span>品牌曝光优先</span></div></div><div className="campaign-monogram">FLORASIS<small>花西子</small></div></section>
          <section className="stats"><div><label>项目总预算</label><strong>$12,000<small>USD</small></strong><span>含 $2,400 服务费 · 演示预算</span></div><div><label>已确认创作者</label><strong>{confirmed.length}<small>/ {state.creators.length} 位推荐</small></strong><span>已确认执行报价 {money(committed)}</span></div><div><label>待审核内容</label><strong>{pending.length}<small>份</small></strong><span>确认文案、画面与版本</span></div><div><label>已发布内容</label><strong>{published.length}<small>份</small></strong><span>发布后更新结果报告</span></div></section>
          <section className="overview-grid"><div className="panel"><div className="panel-heading"><h2>接下来，需要你的确认</h2><span className="soft-label">YOUR NEXT STEP</span></div><button className="action-row" onClick={()=>go("creators")}><span className="action-icon"><Users/></span><div><h3>{state.creators.filter(c=>!c.confirmed).length} 位候选博主，等待你的选择</h3><p>查看内容方向、美国受众与完整合作报价。</p></div><ArrowRight/></button><button className="action-row" onClick={()=>go("review")}><span className="action-icon rose"><Clapperboard/></span><div><h3>{pending.length?`${pending.length} 份内容可以审核`:"查看内容制作进度"}</h3><p>留下反馈，或确认当前版本可以发布。</p></div><ArrowRight/></button><div className="brief-inline"><div><h3>这次推广，我们想做到</h3><button onClick={()=>setBriefOpen(true)}>查看完整需求<ArrowUpRight size={13}/></button></div><p>{state.brief}</p></div></div><div className="panel"><div className="panel-heading"><h2>项目时间线</h2><span>10 月</span></div><div className="timeline">{["需求与策略已确认","确认合作博主","内容制作与审核","内容发布","数据回传与结案"].map((v,i)=><div key={v} className={i===0?"done":i===stage?"current":""}><span>{i===0?<Check size={12}/>:i+1}</span><p>{v}<small>{["已完成",`${confirmed.length} 位已确认`,`${awaiting.length} 位在制作 / 审核`,`${published.length} 份已模拟发布`,"结果与报告在投放结果页查看"][i]}</small></p></div>)}</div></div></section>
          <section className="panel recent"><div className="panel-heading"><h2>最近更新</h2><span>品牌与团队同步</span></div>{state.activity.slice(0,3).map((a,i)=><div className="activity" key={i}><span/><p>{a.text}</p><time>{dateLabel(a.at)}</time></div>)}</section>
        </>}

        {view==="creators"&&<>
          <div className="section-toolbar"><Tabs className="filter-tabs" value={filter} onValueChange={setFilter}><TabsList className="creator-filter-list"><TabsTrigger value="all">全部 {state.creators.length}</TabsTrigger>{platforms.map(platform=><TabsTrigger key={platform} value={platform}>{platform}</TabsTrigger>)}<TabsTrigger value="confirmed">已确认 {confirmed.length}</TabsTrigger></TabsList></Tabs><span className="meta">数据与报价均为示例 · 所有金额 USD</span></div>
          <div className="creator-grid">{filtered.map(c=><article key={c.id} className={`creator-card ${c.selected?"chosen":""}`}>
            <div className="creator-top"><div className="avatar creator-photo" style={{background:c.color}}>{c.photo?<img src={c.photo} alt=""/>:initials(c.name)}</div><div><h2>{c.name}</h2><p>{c.category}</p></div><Checkbox aria-label={`选择 ${c.name}`} checked={c.selected} disabled={disabled||c.confirmed} onCheckedChange={()=>act("toggle",{id:c.id},"推荐名单已更新")}/></div>
            <div className="creator-location"><span><MapPin size={13}/>{c.city}</span><span><Languages size={13}/>{c.languages}</span></div>
            <p className="creator-bio">{c.bio}</p>
            <div className="creator-tags"><span>{c.platform}</span><span>受众 {c.audienceAge}</span><span>美国受众 {c.us}%</span>{c.confirmed&&<span className="green">已确认</span>}</div>
            <div className="creator-metrics"><div><strong>{compact(c.followers)}</strong><small>粉丝量</small></div><div><strong>{compact(c.views)}</strong><small>近期播放中位数</small></div><div><strong>{c.engagement}%</strong><small>示例互动率</small></div></div>
            <div className="reason"><span>WHY WE PICKED</span><p>{c.reason}</p></div>
            <div className="deliverable"><Clapperboard size={15}/><p>{c.deliverables}</p></div>
            <div className="card-bottom"><div><strong>{money(c.quote)}</strong><span>执行报价</span></div><Button variant="outline" onClick={()=>setDetail(c)}>查看详情 <ArrowUpRight size={14}/></Button></div>
          </article>)}</div>
          <div className="selection-bar"><div><strong>已选 {selected.length} 位 · {money(chosenTotal)}</strong><p>执行预算 $9,600 · 剩余 {money(9600-chosenTotal)} · 服务费另列于总预算内</p></div><Button disabled={disabled||!newSelected.length||chosenTotal>9600} onClick={()=>act("confirm",{},"人选确认已保存（演示）")}>确认新增 {newSelected.length} 位 <Check size={16}/></Button></div>
          <p className="data-note">示例指标：最近 12 条短视频播放中位数；互动率按（点赞＋评论）/ 粉丝数计算。展示值用于演示，尚未连接任何平台或服务商。</p>
        </>}

        {view==="review"&&<>
          <div className="section-toolbar">{draftPicker}<span className="meta">{draft?.published?"已模拟发布":last?statusName[last.status]:"等待首版内容"}</span></div>
          <div className="review-grid"><div className="panel review-content"><div className="panel-heading"><h2>{creator?.name} / {shownVersion?.file?"内容稿件":"脚本提案"}</h2>{draft?.versions.length>0&&<Select value={String(versionIndex<0?draft.versions.length-1:versionIndex)} onValueChange={v=>setVersionIndex(Number(v))}><SelectTrigger aria-label="选择内容版本"><SelectValue/></SelectTrigger><SelectContent>{draft.versions.map((v,i)=><SelectItem key={v.id} value={String(i)}>v{v.number}{i===draft.versions.length-1?" · 最新":" · 历史"}</SelectItem>)}</SelectContent></Select>}</div>{shownVersion?<><div className="content-preview">{shownVersion.file?.type.startsWith("video/")?<video key={shownVersion.file.key} controls src={mediaUrl(shownVersion.file.key)}/>:<img src={shownVersion.file?mediaUrl(shownVersion.file.key):"/florasis-demo/florasis-lipstick.jpg"} alt={shownVersion.file?"创作者提交的内容":"花西子官方产品参考图，非创作者作品"}/>}<span>{shownVersion.file?shownVersion.file.name:"品牌产品参考 · 等待内容同步"}</span></div><Tabs defaultValue="script"><TabsList><TabsTrigger value="script">拍摄脚本</TabsTrigger><TabsTrigger value="caption">发布文案</TabsTrigger></TabsList><TabsContent value="script"><p className="copy-block">{shownVersion.script}</p></TabsContent><TabsContent value="caption"><p className="copy-block">{shownVersion.caption}</p></TabsContent></Tabs><div className="review-footer"><span className={`status ${shownVersion.status}`}>{statusName[shownVersion.status]}</span><span>v{shownVersion.number} · {dateLabel(shownVersion.at)}</span></div></>:<div className="empty-state"><Clapperboard/><h3>等待创作者提交首稿</h3><p>稿件准备好后，将通过服务商同步供你查看；当前尚未连接。</p></div>}</div><div className="review-side"><div className="panel"><div className="panel-heading"><h2>反馈与确认</h2><MessageSquare size={17}/></div><div className="comments">{draft?.comments.length?draft.comments.map(c=><div className="comment" key={c.id}><div><strong>{c.author}</strong><time>{dateLabel(c.at)}</time></div><span className="meta">v{draft.versions.find(v=>v.id===c.versionId)?.number}</span><p>{c.text}</p></div>):<div className="quiet-state">还没有反馈。可以先看脚本和文案，再留下具体修改意见。</div>}</div>{!draft?.published&&last&&<><Textarea aria-label="内容反馈" value={comment} onChange={e=>setComment(e.target.value)} placeholder="例如：请增加自然光下的上唇试色，片头缩短到 3 秒。" rows={4}/><Button className="wide" variant="outline" disabled={disabled||!comment.trim()} onClick={async()=>{if(await act("comment",{id:draft.id,text:comment},"修改意见已保存（演示）"))setComment("")}}>提交修改意见</Button><Button className="wide" disabled={disabled||last.status==="approved"||(versionIndex>=0&&versionIndex!==draft.versions.length-1)} onClick={()=>act("approve",{id:draft.id},"最新版本已通过（演示）")}><CheckCircle2 size={17}/> {last.status==="approved"?"最新版本已通过":"确认最新版本可发布"}</Button></>}{draft?.published&&<p className="success-note"><CheckCircle2 size={17}/> 已模拟发布，查看投放结果页。</p>}<p className="data-note">反馈针对最新版本。历史版本保留供对照。当前操作仅演示，不会发送给团队或创作者。</p></div></div></div>
        </>}

        {view==="results"&&<>
          <div className="notice"><ChartNoAxesCombined size={18}/><p>投放数据等待服务商连接。历史演示记录如有保留，仍为虚拟数据，不代表真实曝光或销量。<small>正式项目优先同步服务商数据；缺项通过导出或品牌资料补充。</small></p></div>
          <section className="stats"><div><label>累计播放（模拟）</label><strong>{metricRows.length?compact(views):"—"}</strong><span>按已发布内容累计，不等于独立触达</span></div><div><label>内容互动（模拟）</label><strong>{metricRows.length?compact(engagement):"—"}</strong><span>点赞＋评论＋收藏</span></div><div><label>已发布内容</label><strong>{published.length}<small>/ {confirmed.length}</small></strong><span>以品牌确认的最新版本发布</span></div><div><label>转化订单</label><strong>—</strong><span>尚未接入订单 / 核销数据</span></div></section>
          <div className="results-layout"><div className="panel"><div className="panel-heading"><h2>创作者内容表现</h2><span>演示快照</span></div>{metricRows.length?<><div className="bar-chart">{metricRows.map((r,i)=><div className="bar-group" key={r.creator}><span>{compact(r.views)}</span><div style={{height:`${Math.max(25,r.views/70000*145)}px`,background:["#ff2a2a","#252525","#777777","#bdbdbd"][i%4]}}/><small>{r.creator.split(" ")[0]}</small></div>)}</div><Table><TableHeader><TableRow><TableHead>创作者</TableHead><TableHead>播放</TableHead><TableHead>点赞</TableHead><TableHead>评论</TableHead><TableHead>收藏</TableHead></TableRow></TableHeader><TableBody>{metricRows.map(r=><TableRow key={r.creator}><TableCell>{r.creator}</TableCell><TableCell>{compact(r.views)}</TableCell><TableCell>{r.likes}</TableCell><TableCell>{r.comments}</TableCell><TableCell>{r.saves}</TableCell></TableRow>)}</TableBody></Table></>:<div className="empty-state"><ChartNoAxesCombined/><h3>第一条内容发布后，结果会出现在这里</h3><p>真实发布状态和内容表现将通过服务商同步；当前尚未连接。</p><Button variant="outline" onClick={()=>go("review")}>前往内容审核</Button></div>}</div><div className="panel"><div className="panel-heading"><h2>项目费用</h2><span>USD</span></div><dl className="budget-list"><div><dt>品牌总预算</dt><dd>$12,000</dd></div><div><dt>hOpOn 服务费 · 20%</dt><dd>$2,400</dd></div><div><dt>可用执行预算</dt><dd>$9,600</dd></div><div><dt>已确认执行报价</dt><dd>{money(committed)}</dd></div><div className="total"><dt>待分配执行预算</dt><dd>{money(9600-committed)}</dd></div></dl><p className="data-note">演示账目，无实际收付款。服务费需覆盖团队人工和软件成本，不等于净利润。追加付费推广另行确认。</p></div></div>
          <section className="panel recent"><div className="panel-heading"><h2>发布记录</h2><span>不会向社交平台发帖</span></div>{published.length?published.map(d=><div className="action-row" key={d.id}><span className="action-icon"><Clapperboard size={17}/></span><div><h3>{state.creators.find(c=>c.id===d.creatorId)?.name} · v{d.versions.at(-1)?.number}</h3><p>已模拟发布 · {dateLabel(d.publishedAt!)}</p></div><Button variant="outline" onClick={()=>{selectDraft(d.id);go("review")}}>查看内容</Button></div>):<p className="quiet-state">尚无发布记录。</p>}</section>
        </>}

        {view==="geo"&&<>
          <div className="notice"><Sparkles size={18}/><p>GEO 随创作者推广打包，不单独订阅。本页展示配套报告样例。<small>固定问题集：20 个问题 × 3 个模型 × 2 次采样；英语 / 美国 / 9 月演示样本。所有数值为虚拟。</small></p></div>
          <section className="stats"><div><label>品牌提及率</label><strong>35<small>%</small></strong><span>42 / 120 次示例回答</span></div><div><label>官网引用率</label><strong>18.3<small>%</small></strong><span>22 / 120 次示例回答</span></div><div><label>监测问题</label><strong>20<small>个</small></strong><span>彩妆推荐 / 产品 / 品牌比较</span></div><div><label>AI 来源订单</label><strong>—</strong><span>尚无可核验的归因资料</span></div></section>
          <div className="panel"><div className="panel-heading"><h2>人们问了什么，品牌出现在哪里</h2><span>样本回答概览</span></div><Table><TableHeader><TableRow><TableHead>用户问题（英语 / 美国）</TableHead><TableHead>品牌提及</TableHead><TableHead>官网引用</TableHead><TableHead>诊断</TableHead></TableRow></TableHeader><TableBody>{[["Which Chinese makeup brands are worth exploring?","5 / 6","2 / 6","已有品牌认知"],["What makes Florasis engraved lipstick different?","6 / 6","4 / 6","补充材质与使用信息"],["Best lipstick gifts with artistic packaging?","2 / 6","0 / 6","礼物场景内容不足"]].map(row=><TableRow key={row[0]}>{row.map((x,i)=><TableCell key={i}>{x}</TableCell>)}</TableRow>)}</TableBody></Table><p className="data-note">以上为 20 个问题中的 3 个示例。每个问题共 6 次采样；不构成全网份额或推荐排名承诺。</p></div>
          <div className="recommendation-grid">{[["product","01","完善英文产品信息","核对材质、色号、使用方式与美国购买信息，让来源页面更完整。"],["faq","02","补充礼物与使用场景","围绕产品适合谁、如何使用与常见问题，形成可核实的英文内容。"],["measurement","03","建立来源与订单核验","如品牌已有分析或电商工具，使用现成服务接入；否则定期导出核对。"]].map(([id,no,name,desc])=><div className="panel geo-card" key={id}><span>{no}</span><h3>{name}</h3><p>{desc}</p><Button disabled={disabled} variant={state.geoTasks.includes(id)?"secondary":"outline"} onClick={()=>act("geo",{id},"优化事项已更新")}>{state.geoTasks.includes(id)?<><Check size={15}/> 已加入后续讨论</>:"加入后续讨论"}</Button></div>)}</div>
          <p className="data-note">GEO 可作为推广内含服务，具体内容、周期和限额随项目确认。本页为虚拟报告，尚未连接 GEO 服务商。</p>
        </>}

        <footer className="demo-note">品牌视角演示 · 操作仅保存在当前浏览器，尚未同步到服务商。<br/>花西子项目的创作者、合作、预算与投放结果均为虚构，不代表真实合作或实际投放。各平台与 GEO 真实数据均等待连接，不含真实账号资料。<br/>产品与视觉参考：<a href="https://florasis.com/products/flawless-jade-breathable-pressed-powder" target="_blank" rel="noreferrer">Florasis 官网</a> · 仅供演示。</footer>
      </main>
    </SidebarInset>

    <Dialog open={!!detail} onOpenChange={open=>!open&&setDetail(null)}><DialogContent className="detail-dialog"><DialogHeader><DialogTitle>{detail?.name}</DialogTitle><DialogDescription>虚拟创作者档案 · 用于演示推荐流程</DialogDescription></DialogHeader>{detail&&<><div className="detail-profile detail-hero"><div className="avatar large detail-photo" style={{background:detail.color}}>{detail.photo?<img src={detail.photo} alt={`${detail.name} 示例头像`}/>:initials(detail.name)}</div><div><span className="detail-kicker">{detail.platform} · 示例候选</span><h3>{detail.category}</h3><p><MapPin size={13}/>{detail.city}</p><p><Languages size={13}/>{detail.languages}</p></div></div><p className="body-copy detail-bio">{detail.bio}</p><div className="detail-facts"><div><span>内容专长</span><strong>{detail.specialties.join(" · ")}</strong></div><div><span>核心受众</span><strong>{detail.audienceAge} · 美国受众 {detail.us}%</strong></div></div><h3>推荐理由</h3><p className="body-copy">{detail.reason}</p><h3>内容方向示例</h3><div className="concept-list">{detail.contentConcepts.map(concept=><div className="concept-item" key={concept.title}><FileText size={17}/><div><strong>{concept.title}</strong><p>{concept.description}</p><small>内容方向示例 · 非既有作品</small></div></div>)}</div><h3>交付与报价</h3><p className="body-copy">{detail.deliverables}</p><strong className="detail-price">{money(detail.quote)}</strong><p className="data-note">头像、简介、受众与内容方向为示例资料；未连接账号，不代表真实合作或既有作品。改稿次数、档期、授权期限与追加广告使用权须在正式合作中确认。</p></>}</DialogContent></Dialog>
    <Dialog open={briefOpen} onOpenChange={setBriefOpen}><DialogContent><DialogHeader><DialogTitle>项目需求</DialogTitle><DialogDescription>花西子 · 美国秋季推广 / 虚拟 brief</DialogDescription></DialogHeader><p className="body-copy">{state.brief}</p></DialogContent></Dialog>
  </SidebarProvider>
}
